services:
  minio:
    image: minio/minio
    container_name: minio
    command: server --address ":9000" --console-address ":9090" /data
    restart: always
    environment:
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
      MINIO_ROOT_USER: ${MINIO_USER}
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - "data:/data"
volumes:
  data: